"""Explanation Engine.

Generates human-readable reasons for a candidate's fit score.

Critical constraint: cosine similarity between two embedding vectors is a
single opaque number — it does NOT tell you which specific words or phrases
drove that score. So this engine does NOT try to "explain the embedding."
Instead it runs a separate, fully transparent keyword/skill overlap check
between the job text and resume text, and reports exactly what it found.

This means every bullet below is independently verifiable: re-run the same
keyword extraction and you get the same matched/missing terms, every time.
Nothing here is generated by an LLM and nothing is inferred from the
embedding score itself.
"""

import re
from dataclasses import dataclass


# A deliberately small, explicit skill vocabulary. This is NOT a learned
# model — it's a fixed list we check for literal (case-insensitive)
# presence in text. Extend this list as EVIDIQ's target roles expand; do
# not replace it with fuzzy/inferred matching without re-validating that
# every bullet stays traceable to actual matched text.
KNOWN_SKILLS = [
    "python", "fastapi", "django", "flask",
    "machine learning", "deep learning", "nlp",
    "rag", "llm", "langgraph", "langchain",
    "pytorch", "tensorflow", "scikit-learn", "sklearn",
    "docker", "kubernetes", "deployment", "production",
    "sql", "postgresql", "postgres", "mongodb",
    "vector database", "qdrant", "chromadb", "pinecone",
    "react", "next.js", "typescript", "javascript",
    "aws", "gcp", "azure", "ci/cd",
    "api", "rest", "microservices",
]


@dataclass(frozen=True)
class ExplanationResult:
    matched_skills: list[str]
    missing_skills: list[str]
    positives: list[str]   # "+ ..." style bullets
    negatives: list[str]   # "- ..." style bullets


def _extract_skills(text: str) -> set[str]:
    """Find which known skills literally appear in the given text.

    Case-insensitive substring match against KNOWN_SKILLS. This is
    intentionally simple (no stemming, no fuzzy match) so every result is
    exactly reproducible and explainable: "found" means the literal phrase
    is present in the text, nothing more, nothing less.
    """
    lowered = text.lower()
    found = set()

    for skill in KNOWN_SKILLS:
        # Word-boundary-ish check so "sql" doesn't match inside "postgresql"
        # incorrectly skip — using regex word boundaries where the skill
        # has no special characters; falls back to plain substring for
        # multi-word or symbol-containing skills like "ci/cd".
        if re.search(r"\b" + re.escape(skill) + r"\b", lowered):
            found.add(skill)

    return found


def explain_score(*, job_text: str, resume_text: str) -> ExplanationResult:
    """Build traceable explanation bullets from literal skill overlap.

    Args:
        job_text: the active job description text.
        resume_text: the parsed resume text for this candidate.

    Returns:
        ExplanationResult with matched/missing skills and ready-to-display
        positive/negative bullet strings.
    """
    job_skills = _extract_skills(job_text)
    resume_skills = _extract_skills(resume_text)

    matched = sorted(job_skills & resume_skills)
    missing = sorted(job_skills - resume_skills)

    positives = [f"Demonstrates {skill}" for skill in matched]
    negatives = [f"No evidence of {skill}" for skill in missing]

    # Cap the number of bullets shown so the UI doesn't get a wall of text
    # for JDs with many requirements — keep the strongest signal visible.
    MAX_BULLETS = 5
    positives = positives[:MAX_BULLETS]
    negatives = negatives[:MAX_BULLETS]

    return ExplanationResult(
        matched_skills=matched,
        missing_skills=missing,
        positives=positives,
        negatives=negatives,
    )